Initial CNNs using pytorch

In [8]:
import torch
import torch.nn as nn

In [9]:
def pth_conv(input, kernel, stride=1, padding=0):
    #input - N C H W (batch_size, Channels, H x W)
    # in_channels, out_channels, bias, stride, padding

    #kernel - out, in, kh, kw
    out_channels, in_channels, kh, kw = kernel.shape
    conv_layer = nn.Conv2d(in_channels, out_channels, kernel_size= (kh, kw), bias=False, stride=stride, padding=padding)
    conv_layer.weight = nn.Parameter(kernel)
    return conv_layer(input)

In [10]:
input = torch.tensor([[1,2,3],[4,5,6],[7,8,9]]).unsqueeze(0).unsqueeze(0).float()
kernel = torch.tensor([[1,0],[0,1]]).unsqueeze(0).unsqueeze(0).float()
output = pth_conv(input, kernel)
print(output)
assert torch.equal(output, torch.tensor([[[[6,8],[12,14]]]]))

tensor([[[[ 6.,  8.],
          [12., 14.]]]], grad_fn=<ConvolutionBackward0>)


In [11]:
input = torch.tensor([[1,2,3],[4,5,6],[7,8,9]]).unsqueeze(0).unsqueeze(0).float()
kernel = torch.tensor([[1,0],[0,1]]).unsqueeze(0).unsqueeze(0).float()
output = pth_conv(input, kernel, stride=2)
print(output)
assert torch.equal(output, torch.tensor([[[[6]]]]))

tensor([[[[6.]]]], grad_fn=<ConvolutionBackward0>)


In [12]:
input = torch.tensor([[1,2,3],[4,5,6],[7,8,9]]).unsqueeze(0).unsqueeze(0).float()
kernel = torch.tensor([[0,0],[0,0]]).unsqueeze(0).unsqueeze(0).float()
output = pth_conv(input, kernel)
print(output)
assert torch.equal(output, torch.tensor([[[[0,0],[0,0]]]]))

tensor([[[[0., 0.],
          [0., 0.]]]], grad_fn=<ConvolutionBackward0>)
